### PR TITLE
DRAFT: Improve packaging

### PR DESCRIPTION
**Pull request by bioinfornatics**
Python project organization and its process to build it can be enhanced in order to follow best practices.
This is not intended to be yet working as a non lotus developer

### CODE REVIEW

**Comment by mnida** [comment]
Awesome work @bioinfornatics. I'll leave @diego-escobedo to review and finish this PR.

**Comment by bioinfornatics** [comment]
Thanks I hope that will help.
Here I used a combination of:
- namespace pep420 
- src dir: https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html
Indeed I have in mind: Test outside dir
- docker builer pattern to avoid development files into the production containers

Thing not yet cover:
1. Use of configparser andpkg_ressource to separate config and buisness logic (lotus.backend.setting)
2. Investigate the production container in order to be smaller

**Comment by diego-escobedo** [comment]
Looks great so far! Let me know when you take this off draft and I'll review + merge 🪷

**Comment by diego-escobedo** [comment]
Hey @bioinfornatics checked out your branch and took a look. Think there is some confusion about the file structure originally. First of all, great articles you sent (https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html, which is based on https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure%3E). However, the django project itself is not considered a package. 

- The Django app itself is all completely contained within the `backend` folder, since we're following a monorepo model. Therefore, you can think of the inside of that folder as the root of the project. 
- https://docs.djangoproject.com/en/4.1/intro/reusable-apps/#your-project-and-your-reusable-app this is a good summary of how a django project should be structured (the equivalent of mysite in the example would be `backend` for us).
> A Django application is a Python package that is specifically intended for use in a Django project. An application may use common Django conventions, such as having models, tests, urls, and views submodules.
- in this case, our two apps (`api` and `metering_billing`)  would each be considered a package, and could in theory follow the format you mentioned about `src/`. However, they're 1. not ready for publication to PyPi or anything, 2. not really independent. `metering_billing` is a superset of `api`, the latter we created in order to have a stable set of APIs (hence the name) we could isolate from the quickly changing application code we use in the frontend. However, there's a ton of model reuse between them so they're not truly independent. So, essentially a monolith disguised as 2 apps. 
- In theory we would have a tests folder for each app, but right now we just have one for the main project at the outer level. Gets picked up fine by pytest so shouldn't be a huge problem. 
- In order to fix the issue's you're seeing, I would turn the paths `backend/src/lotus/backend/*` back to how they are on the main repo. The apps (`api` and `metering_billing`) at the same level as the `lotus` folder containing asgi.py, wsgi.py, and all the other django project utilities. This will likely fix the import issues you're having. 

You might see this all and think its a bit of a mess, and you'd be partially correct. Transitioning from a monolith into a modular architecture is a longer term project for us, and we're actually doing it by spinning out certain services in Go as we form stronger opinions on the exact domains a billing system should have. You can check out the first one we're working on, an event ingestion service. 

Please let me know if I can help with anything else or answer any other questions.

**Comment by diego-escobedo** [comment]
See https://github.com/uselotus/lotus/issues/530#issuecomment-1465109927

**Pull request closed without merging**
