### PR TITLE
Resolve "Improve Error Messaging + Validation for Tiers in Plan Component"

### LINKED ISSUE #325: Improve Error Messaging + Validation for Tiers in Plan Component
**Is your feature request related to a problem? Please describe.**
The only response we get back if we input invalid tiers is the Tiers are not valid response. This can be confusing to debug or figure out what you did wrong.

**Describe the solution you'd like**
An message relevant to the type of validation issue, either ranges are not correct or units are not correct etc.

In addition, if the border around the relevant cell could become red, signaling the location of the error that would be an additional improvement.

### PR DESCRIPTION
**Pull request by glamboyosa**
Closes #325 
this PR implements the feature request for better error messaging in the app. 

if an `EditableRow` has an error it: 
- displays the appropriate error message 
- disables "Add Tier" button so you cannot create a new tier. previously you could create N more tiers which would be errored. 
- disables "Create new component" button as well. 

the validation function returns an array of objects with two fields `isValid` a Boolean if the current element is valid and a message which is a string which we render as our error message. 

we then simply check if the array has any false `isValid` values whenever a new `EditableRow` gets rendered and if we do error handling and disabling kicks in to again, prevent stacking up errors and inform the user they made a mistake.

### CODE REVIEW

**Comment by glamboyosa** [comment]
The nice-to-haves: Can't be implemented by me as a `key` prop is required for `Tiers` . the key could be an id just something distinct and auto-incrementing. The key would be used by automatically antd as the `data-row-key` prop. 

We could then grab the `tr` by the data attribute on render or click and we can then add a red border to the element which has the error. 

Of course that's just a rough idea of how i would do it (spitballing). It could be implemented in other ways.

**Comment by glamboyosa** [comment]
Please let me know if you have any questions.

**Comment by mnida** [comment]
@glamboyosa Looks good, merging soon!

**Comment by glamboyosa** [comment]
nice!

**Pull request merged**
