### PR TITLE
Resolve "Optimistic UI For Plan Tags"

### PR DESCRIPTION
**Pull request by glamboyosa**
## Closes 
Closes LOT-547

## Description 
This MR adds optimistic UI. Well, actually it basically does a search and replace on tags instead of a whole HTTP req. making things faster.

### CODE REVIEW

**Review by mnida — CHANGES_REQUESTED** [review]
Found a bug related to planId not being found. Check this loom @glamboyosa. https://www.loom.com/share/705d57ba31b64380b7b48478f8e6bd3a

In addition, is this something we can apply on the plandetails page or will it not make much of a difference?

**Comment by glamboyosa** [comment]
very little diff.

**Comment by glamboyosa** [comment]
the point was that we were refetching all plans so doing a search & replace makes sense. Individual plan page is pretty chill.

**Comment by mnida** [comment]
Sounds good @glamboyosa

**Review by mnida — APPROVED** [review]

**Pull request merged**
