### PR TITLE
Feature/self host no build

### PR DESCRIPTION
**Pull request by husseinmkwizu**

### CODE REVIEW

**Comment by mnida** [comment]
Hi @husseinmkwizu , just making sure this was closed on purpose and you aren't still dealing with any issues?

**Comment by husseinmkwizu** [comment]
Hi @mnida, I had an issue where it was taking too long to build all the images and if one fails i had to start all over again. So i built the images one by one manually and created a new self host script that just runs from the already built images.

In its current form, the PR might not be very useful to the larger audience that’s why i closed it, but might be useful if these prebuilt images are hosted by lotus.

I think it’s better to pre build the images for self hosting use case. For dev work, it’s ok to build from source. What do you think? I am open to contribute to this.

**Comment by mnida** [comment]
Hi @husseinmkwizu , let me look more into this and come back to you later today

**Comment by husseinmkwizu** [comment]
@mnida ok noted.

**Pull request closed without merging**
