### PR TITLE
Resolve "Move from React-Query to TanStack"

### PR DESCRIPTION
**Pull request by glamboyosa**
## Closes 
LOT-464. 

## Description 

This MR moves React Query to Tanstack Query. 

## Acceptance Criteria 
- UI should be the same. 
- HTTP network requests should work, still.

### CODE REVIEW

**Comment by mnida** [comment]
Weird, this messes up ant design styling for text and buttons

**Comment by glamboyosa** [comment]
very weird. happened yesterday. also worth nothing cd frontend && npm run dev isn't messed uo

**Comment by mnida** [comment]
Hmm I will take a look more into it @glamboyosa . Most likely has to do with yarn changes but can't see it in the diffs. Luckily this isn't an urgent PR so we can spend a few extra hours trying to fix

**Comment by mnida** [comment]
Wasn't able to understand this today @glamboyosa

**Comment by glamboyosa** [comment]
Closing and opening a new one. again.

**Pull request closed without merging**
